"""
Template service for customizable briefings, summaries, and responses.

Provides:
- System default templates
- User custom templates
- Organization shared templates
- Template rendering with variables
"""

import re
from typing import Optional, List, Dict, Any
from datetime import datetime

from sqlalchemy.orm import Session

from models import Template, TemplateType, User


# =============================================================================
# DEFAULT SYSTEM TEMPLATES
# =============================================================================

SYSTEM_TEMPLATES = [
    {
        "name": "Default Briefing",
        "template_type": TemplateType.BRIEFING,
        "description": "Standard pre-meeting briefing template",
        "content": """# Pre-Meeting Briefing: {{meeting_title}}

**Scheduled:** {{meeting_time}}
**Duration:** {{meeting_duration}}
**Type:** {{meeting_type}}

## Participants
{{#participants}}
- **{{name}}** ({{role}})
  - Previous interactions: {{interaction_count}}
  - Key points to remember: {{key_points}}
{{/participants}}

## Suggested Topics
{{#topics}}
- {{topic}}
{{/topics}}

## Prepared Questions
{{#questions}}
1. {{question}}
{{/questions}}

## Background Context
{{context_notes}}

---
*Generated by ReadIn AI*
""",
        "variables": ["meeting_title", "meeting_time", "meeting_duration", "meeting_type",
                      "participants", "topics", "questions", "context_notes"],
    },
    {
        "name": "Default Summary",
        "template_type": TemplateType.SUMMARY,
        "description": "Standard meeting summary template",
        "content": """# Meeting Summary: {{meeting_title}}

**Date:** {{meeting_date}}
**Duration:** {{duration}}
**Participants:** {{participant_count}}

## Key Points
{{#key_points}}
- {{point}}
{{/key_points}}

## Decisions Made
{{#decisions}}
- {{decision}}
{{/decisions}}

## Action Items
{{#action_items}}
- [ ] **{{assignee}}**: {{description}} (Due: {{due_date}})
{{/action_items}}

## Topics Discussed
{{#topics}}
- {{topic}} ({{sentiment}})
{{/topics}}

## Next Steps
{{next_steps}}

---
*Generated by ReadIn AI*
""",
        "variables": ["meeting_title", "meeting_date", "duration", "participant_count",
                      "key_points", "decisions", "action_items", "topics", "next_steps"],
    },
    {
        "name": "Bullet Point Response",
        "template_type": TemplateType.RESPONSE,
        "description": "Concise bullet point responses for quick glancing",
        "content": """**Quick Answer:**
{{#points}}
• {{point}}
{{/points}}

{{#if additional_context}}
**More Detail:** {{additional_context}}
{{/if}}
""",
        "variables": ["points", "additional_context"],
    },
    {
        "name": "Detailed Response",
        "template_type": TemplateType.RESPONSE,
        "description": "Comprehensive response with context",
        "content": """**Answer:**
{{main_response}}

**Key Considerations:**
{{#considerations}}
- {{item}}
{{/considerations}}

**Supporting Points:**
{{#supporting_points}}
- {{point}}
{{/supporting_points}}
""",
        "variables": ["main_response", "considerations", "supporting_points"],
    },
]


class TemplateService:
    """
    Service for managing and rendering templates.
    """

    def __init__(self, db: Session):
        self.db = db

    def initialize_system_templates(self):
        """Create default system templates if they don't exist."""
        for template_data in SYSTEM_TEMPLATES:
            existing = self.db.query(Template).filter(
                Template.name == template_data["name"],
                Template.is_system == True,
            ).first()

            if not existing:
                template = Template(
                    name=template_data["name"],
                    template_type=template_data["template_type"],
                    description=template_data["description"],
                    content=template_data["content"],
                    variables=template_data["variables"],
                    is_system=True,
                    is_default=True,
                )
                self.db.add(template)

        self.db.commit()

    def get_template(
        self,
        template_type: str,
        user_id: Optional[int] = None,
        organization_id: Optional[int] = None,
        template_name: Optional[str] = None,
    ) -> Optional[Template]:
        """
        Get the appropriate template for a user.

        Priority:
        1. User's custom template (if specified by name)
        2. User's default template for type
        3. Organization's template
        4. System default template
        """
        # Try user's specific template
        if user_id and template_name:
            template = self.db.query(Template).filter(
                Template.user_id == user_id,
                Template.name == template_name,
                Template.is_active == True,
            ).first()
            if template:
                return template

        # Try user's default for type
        if user_id:
            template = self.db.query(Template).filter(
                Template.user_id == user_id,
                Template.template_type == template_type,
                Template.is_default == True,
                Template.is_active == True,
            ).first()
            if template:
                return template

        # Try organization template
        if organization_id:
            template = self.db.query(Template).filter(
                Template.organization_id == organization_id,
                Template.template_type == template_type,
                Template.is_default == True,
                Template.is_active == True,
            ).first()
            if template:
                return template

        # Fall back to system template
        return self.db.query(Template).filter(
            Template.template_type == template_type,
            Template.is_system == True,
            Template.is_default == True,
        ).first()

    def get_user_templates(
        self,
        user_id: int,
        template_type: Optional[str] = None,
    ) -> List[Template]:
        """Get all templates available to a user."""
        query = self.db.query(Template).filter(
            (Template.user_id == user_id) | (Template.is_system == True),
            Template.is_active == True,
        )

        if template_type:
            query = query.filter(Template.template_type == template_type)

        return query.order_by(Template.is_system, Template.name).all()

    def create_template(
        self,
        user_id: int,
        name: str,
        template_type: str,
        content: str,
        description: Optional[str] = None,
        variables: Optional[List[str]] = None,
        is_default: bool = False,
        organization_id: Optional[int] = None,
    ) -> Template:
        """Create a new user template."""
        # Extract variables from content if not provided
        if variables is None:
            variables = self._extract_variables(content)

        # If setting as default, unset other defaults
        if is_default:
            self.db.query(Template).filter(
                Template.user_id == user_id,
                Template.template_type == template_type,
                Template.is_default == True,
            ).update({"is_default": False})

        template = Template(
            user_id=user_id,
            organization_id=organization_id,
            name=name,
            template_type=template_type,
            description=description,
            content=content,
            variables=variables,
            is_default=is_default,
        )

        self.db.add(template)
        self.db.commit()
        self.db.refresh(template)

        return template

    def update_template(
        self,
        template_id: int,
        user_id: int,
        **updates,
    ) -> Optional[Template]:
        """Update an existing template."""
        template = self.db.query(Template).filter(
            Template.id == template_id,
            Template.user_id == user_id,
            Template.is_system == False,
        ).first()

        if not template:
            return None

        for key, value in updates.items():
            if hasattr(template, key) and value is not None:
                setattr(template, key, value)

        # Re-extract variables if content changed
        if "content" in updates:
            template.variables = self._extract_variables(template.content)
            template.version += 1

        self.db.commit()
        self.db.refresh(template)

        return template

    def delete_template(self, template_id: int, user_id: int) -> bool:
        """Delete a user template."""
        template = self.db.query(Template).filter(
            Template.id == template_id,
            Template.user_id == user_id,
            Template.is_system == False,
        ).first()

        if not template:
            return False

        self.db.delete(template)
        self.db.commit()
        return True

    def render_template(
        self,
        template: Template,
        variables: Dict[str, Any],
    ) -> str:
        """
        Render a template with provided variables.

        Supports:
        - Simple variables: {{variable_name}}
        - Loops: {{#items}}...{{/items}}
        - Conditionals: {{#if condition}}...{{/if}}
        """
        content = template.content

        # Handle loops
        loop_pattern = r'\{\{#(\w+)\}\}(.*?)\{\{/\1\}\}'
        for match in re.finditer(loop_pattern, content, re.DOTALL):
            var_name = match.group(1)
            loop_content = match.group(2)

            if var_name in variables and isinstance(variables[var_name], list):
                rendered_items = []
                for item in variables[var_name]:
                    item_content = loop_content
                    if isinstance(item, dict):
                        for key, value in item.items():
                            item_content = item_content.replace(f'{{{{{key}}}}}', str(value or ''))
                    else:
                        item_content = item_content.replace('{{item}}', str(item))
                    rendered_items.append(item_content.strip())
                content = content.replace(match.group(0), '\n'.join(rendered_items))
            else:
                content = content.replace(match.group(0), '')

        # Handle conditionals
        if_pattern = r'\{\{#if (\w+)\}\}(.*?)\{\{/if\}\}'
        for match in re.finditer(if_pattern, content, re.DOTALL):
            var_name = match.group(1)
            if_content = match.group(2)

            if variables.get(var_name):
                content = content.replace(match.group(0), if_content)
            else:
                content = content.replace(match.group(0), '')

        # Handle simple variables
        for var_name, value in variables.items():
            if not isinstance(value, (list, dict)):
                content = content.replace(f'{{{{{var_name}}}}}', str(value or ''))

        # Clean up any remaining unmatched variables
        content = re.sub(r'\{\{[^}]+\}\}', '', content)

        return content.strip()

    def _extract_variables(self, content: str) -> List[str]:
        """Extract variable names from template content."""
        # Find all {{variable}} patterns
        simple_vars = re.findall(r'\{\{(\w+)\}\}', content)

        # Find all {{#loop}} patterns
        loop_vars = re.findall(r'\{\{#(\w+)\}\}', content)

        # Find all {{#if condition}} patterns
        if_vars = re.findall(r'\{\{#if (\w+)\}\}', content)

        # Combine and deduplicate
        all_vars = list(set(simple_vars + loop_vars + if_vars))

        return sorted(all_vars)
