# Safety Policy - Ignored Vulnerabilities
# These vulnerabilities have been reviewed and accepted

version: "3.0"
security:
  ignore-vulnerabilities:
    # ecdsa vulnerabilities - all versions affected, no fix available
    # The library has fundamental design limitations with Python primitives
    # These are side-channel attack vectors which require local access
    # We use cryptography library for production ECDSA operations
    - id: 64459
      reason: "CVE-2024-23342 - Minerva attack affects all ecdsa versions. No fix available. Using cryptography library for production."
      expires: "2027-01-01"
    - id: 64396
      reason: "PVE-2024-64396 - Side-channel vulnerability affects all Python ecdsa versions. Inherent Python limitation. Not exploitable remotely."
      expires: "2027-01-01"
